# ── BASE ──────────────────────────────────────────────
services:

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  db-importer:
    build:
      context: ./etl
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      JSONL_PATH: /data/raw-wiktextract-data.jsonl.gz
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - seed
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      mysql:
        condition: service_healthy

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - backend

volumes:
  mysql_data:
