# ── PROD override ─────────────────────────────────────
services:

  mysql:
    container_name: mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PROD_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_PROD_USER}
      MYSQL_PASSWORD: ${MYSQL_PROD_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_PROD_DATABASE}
    ports:
      - "3306:3306"
    restart: unless-stopped

  db-importer:
    container_name: db-importer-prod
    environment:
      MYSQL_USER: ${MYSQL_PROD_USER}
      MYSQL_PASSWORD: ${MYSQL_PROD_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_PROD_DATABASE}

  backend:
    container_name: backend-prod
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${MYSQL_PROD_USER}
      DB_PASSWORD: ${MYSQL_PROD_PASSWORD}
      DB_NAME: ${MYSQL_PROD_DATABASE}
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped

  # frontend:
  #   container_name: frontend-prod
  #   ports:
  #     - "80:80"
  #   restart: unless-stopped
